version: '3.8'

services:

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=analytics
    ports:
      - "5434:5432"
    volumes:
      - ./db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    depends_on:
      - postgres
    ports:
      - "8200:8978"
    volumes:
      - .workspace:/opt/cloudbeaver/workspace
    networks:
      - network

volumes:
  data:

networks:
  network:
    driver: bridge