version: '3.8'

services:

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=analytics
    ports:
      - "5434:5432"
    networks:
      - network

volumes:
  data:

networks:
  network:
    driver: bridge